; PlatformIO Project Configuration File
; Robot KRSBI Beroda - ESP32

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino

; Kecepatan Serial Monitor (sesuaikan dengan Serial.begin di kode)
monitor_speed = 115200

; Kecepatan Upload (CachyOS/Linux sangat stabil di 921600)
upload_speed = 921600

; Library Dependencies (Otomatis download dari internet)
lib_deps =
    madhephaestus/ESP32Servo @ ^1.1.2
    knolleary/PubSubClient @ ^2.8

; Build Flags (Opsional, untuk optimasi build)
build_flags = 
    -D CORE_DEBUG_LEVEL=0